language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
# command to run tests
script:
  - wget "http://files.opentreeoflife.org/ott/ott3.3/ott3.3.tgz"
  - tar -xzvf ott3.3.tgz
  - ./run_tests.sh

after_success:
  - codecov
