language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
# command to run tests
script:
  - ./run_tests.sh

after_success:
  - codecov