{% set name = "python-opentree" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenTreeOfLife/python-opentree/archive/v_{{ version }}.tar.gz
  sha256: 948e509df8ab0bf476f75f34a6b9e1803be4f71e1d5812c930f24173fc124130

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python
    - pip
  skip:
  run:
    - python
    - requests>=2.18
    - DendroPy>=4.4.0
    - m2r
    - setuptools

test:
  imports:
    - opentree
  requires:
    - python
    - pip
    - nosetests
  commands:
    - pip check
    - nosetests opentree --with-coverage --cover-branches --cover-package=opentree

about:
  home: https://opentree.readthedocs.io/en/latest
  summary: 'Python package for working with Open Tree of Life webservices and artifacts. Importable as opentree'
  description: |
    This package is a python library designed to make it easier to work with web
    services and data resources associated with the Open Tree of Life project.
  license: BSD-2-Clause
  license_family: BSD
  license_file: License.txt
  doc_url: https://opentree.readthedocs.io/en/latest
  dev_url: https://github.com/OpenTreeOfLife/python-opentree

extra:
  recipe-maintainers:
    - harmsm
    - snacktavish
